import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {loadHost,resolveRole,TOOL_ROOT} from '../src/config.mjs';
import {readJson,atomicJson} from '../src/core.mjs';
import {prepareRequest,buildCommand} from '../src/adapter.mjs';
import {checkRuntime} from '../src/runtime.mjs';
import {parseTranscript,pageResult,validateResult} from '../src/result.mjs';
import {verifySmoke} from '../scripts/live-smoke.mjs';
import {configurationSnapshot,editBindings} from '../src/config-editor.mjs';

function temporary(t) {const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aw-contract-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('configuration editor: validated preview, atomic batch save and stale revision protection',async t=>{
  const dir=temporary(t),file=path.join(dir,'host.json'),raw=readJson(path.join(TOOL_ROOT,'config/home.example.json'));
  raw.catalog=path.join(TOOL_ROOT,'config/roles.json');atomicJson(file,raw);
  const original=fs.readFileSync(file,'utf8'),before=configurationSnapshot(file);
  const request={revision:before.revision,changes:[{role:'reviewer',patch:{effort:'medium'}},{role:'designer',patch:{enabled:false}}]};
  const preview=await editBindings(file,request);assert.equal(preview.changes.length,2);assert.equal(fs.readFileSync(file,'utf8'),original);
  const saved=await editBindings(file,{...request,write:true});
  assert.equal(saved.snapshot.roles.find(r=>r.id==='reviewer').binding.effort,'medium');
  assert.equal(readJson(file).bindings.designer.enabled,false);assert.deepEqual(readJson(file).providers,raw.providers);
  assert.equal(resolveRole(loadHost(file),'reviewer',dir).effort,'medium');
  await assert.rejects(editBindings(file,{...request,write:true}),{code:'config_conflict'});
  const validBytes=fs.readFileSync(file,'utf8');
  await assert.rejects(editBindings(file,{changes:[{role:'reviewer',patch:{effort:'xhigh'}}],write:true}),{code:'unsupported_effort'});
  await assert.rejects(editBindings(file,{changes:[{role:'reviewer',patch:{access:'workspace-write'}}],write:true}),{code:'permission_escalation'});
  assert.equal(fs.readFileSync(file,'utf8'),validBytes);
});
test('configuration contract: host binding, project restrictions and explicit overrides',t=>{
  const dir=temporary(t), host=readJson(path.join(TOOL_ROOT,'config/home.example.json'));
  host.catalog=path.join(TOOL_ROOT,'config/roles.json');host.providers['claude-local'].executable=process.execPath;
  atomicJson(path.join(dir,'host.json'),host);
  const h=loadHost(path.join(dir,'host.json'));
  const selected=resolveRole(h,'reviewer',dir,{effort:'medium'});
  assert.equal(selected.effort,'medium');assert.equal(selected.provider.adapter,'claude');
  assert.throws(()=>resolveRole(h,'reviewer',dir,{effort:'xhigh'}),{code:'unsupported_effort'});
  assert.throws(()=>resolveRole(h,'reviewer',dir,{model:'unconfigured'}),{code:'unsupported_model'});
  assert.equal(resolveRole(h,'developer-main',dir).runnable,false);
  atomicJson(path.join(dir,'agent-workflow.json'),{schema_version:1,allowed_roles:['designer'],instructions:[]});
  assert.throws(()=>resolveRole(h,'reviewer',dir),{code:'role_not_allowed'});
  const nested=path.join(dir,'src');fs.mkdirSync(nested);
  assert.throws(()=>resolveRole(h,'reviewer',nested),{code:'role_not_allowed'});
  atomicJson(path.join(nested,'agent-workflow.json'),{schema_version:1,allowed_roles:['designer','reviewer'],instructions:[]});
  assert.throws(()=>resolveRole(h,'reviewer',nested),{code:'role_not_allowed'});
  fs.writeFileSync(path.join(dir,'policy.md'),'Root instructions must reach the host.');
  atomicJson(path.join(dir,'agent-workflow.json'),{schema_version:1,allowed_roles:['developer-basic'],instructions:['policy.md'],workflows:{implement:'developer-basic'}});
  const hostRole=resolveRole(h,null,dir,{workflow:'implement'});assert.equal(hostRole.role.execution,'host');assert.match(hostRole.project_instructions[0].text,/Root instructions/);
  assert.equal(hostRole.model,null);assert.equal(hostRole.provider,null);
  assert.throws(()=>resolveRole(h,'developer-basic',dir,{model:'configured-model'}),{code:'host_model_not_configurable'});
  h.bindings['developer-basic']={...h.bindings['developer-basic'],execution:'worker',access:'read-only',provider:'codex-local',model:'gpt-6-astra'};
  const worker=resolveRole(h,null,dir,{workflow:'implement'});assert.equal(worker.role.execution,'worker');assert.equal(worker.role.can_delegate,false);assert.equal(worker.role.access,'read-only');
  assert.throws(()=>resolveRole(h,'reviewer',dir,{workflow:'implement'}),{code:'workflow_conflict'});
  h.providers['codex-local'].executable=dir;
  assert.equal(resolveRole(h,'developer-basic',dir).unavailable_reason,'missing_executable');
  atomicJson(path.join(dir,'package.json'),{version:'2.25.0'});atomicJson(path.join(dir,'aw-patch.json'),{patch_id:'aw-prepared-v1',sha256:{}});
  assert.equal(checkRuntime(dir).available,false);
  fs.writeFileSync(path.join(dir,'duplicate.json'),'{"roles":{"x":1,"\\u0078":2}}');
  assert.throws(()=>readJson(path.join(dir,'duplicate.json')),{code:'duplicate_key'});
  assert.ok(Object.values(loadHost(path.join(TOOL_ROOT,'config/office.example.json')).bindings).filter(b=>b.execution!=='host').every(b=>!b.enabled));
});
test('request and adapter boundary: no shell, no inherited API credential, no session fork',t=>{
  const dir=temporary(t), h=loadHost(path.join(TOOL_ROOT,'config/home.example.json'));
  const s=resolveRole(h,'reviewer',dir);
  fs.writeFileSync(path.join(dir,'evidence.txt'),'evidence');
  fs.symlinkSync(os.tmpdir(),path.join(dir,'outside'),process.platform==='win32'?'junction':'dir');
  assert.throws(()=>prepareRequest(s,{goal:'review',acceptance:['valid'],read_paths:['outside']}),{code:'path_not_allowed'});
  const request=prepareRequest(s,{goal:'literal `$(not-a-command)`',acceptance:['valid'],read_paths:['evidence.txt']});
  assert.ok(request.prompt.includes('$(not-a-command)'));
  const before=process.env.ANTHROPIC_API_KEY;process.env.ANTHROPIC_API_KEY='test-boundary-value';
  try {
    const c=buildCommand(s,path.join(dir,'prompt.txt'),path.join(dir,'receipt.json'),30,'session-1');
    assert.equal(c.env.ANTHROPIC_API_KEY,undefined);assert.equal(c.env.AW_WORKER,'1');
    assert.equal(c.args[c.args.indexOf('--resume')+1],'session-1');
    assert.ok(!c.args.includes('--fork-session'));assert.ok(!c.args.includes('--dangerously-skip-permissions'));
    assert.equal(c.args[c.args.indexOf('--tools')+1],'');
    assert.match(request.prompt,/Evidence bundle/);
    assert.ok(!c.args.includes(request.prompt));
  } finally {if(before===undefined)delete process.env.ANTHROPIC_API_KEY;else process.env.ANTHROPIC_API_KEY=before;}
});
test('result contract: complete Unicode pagination preserves blockers; provider errors fail',async t=>{
  const dir=temporary(t), file=path.join(dir,'stdout.log');
  const data={summary:'鹈鹕🚲'.repeat(100),findings:[{severity:'blocker',location:'file:3',trigger:'missing input',impact:'wrong result',evidence:'input absent'}],evidence_refs:['file:3'],uncertainties:['not executed'],payload:{detail:'kept'}};
  const event={type:'result',is_error:false,session_id:'s1',structured_output:data};
  fs.writeFileSync(file,JSON.stringify({type:'system',subtype:'init',model:'configured'})+'\n'+JSON.stringify(event)+'\n');
  const parsed=await parseTranscript(file), limits={summary_max_chars:100,result_page_max_chars:100};
  const summary=pageResult(parsed,limits);
  assert.equal(Array.from(summary.summary).length,100);assert.equal(summary.finding_counts.blocker,1);assert.equal(summary.completeness.summary_truncated,true);
  let cursor=0, full='';do{const page=pageResult(parsed,limits,cursor);full+=page.text;cursor=page.completeness.next_cursor;}while(cursor!==null);
  assert.deepEqual(JSON.parse(full),data);assert.equal(parsed.usage,null);
  const incomplete={...data,findings:[],payload:{verdict:'incomplete',acceptance_checks:['Static inspection'],unverified_checks:['Runtime validation is missing'],scope:'interface'}};
  validateResult(incomplete,'review');const visible=pageResult({...parsed,data:incomplete},limits);
  assert.equal(visible.verdict,'incomplete');assert.equal(visible.unverified_check_count,1);assert.match(visible.unverified_checks[0],/Runtime/);
  assert.throws(()=>validateResult({...incomplete,payload:{...incomplete.payload,verdict:'pass'}},'review'),{code:'invalid_result'});
  const smoke={...parsed,tools:['Read','Glob','Grep'],reads:[],data:{...data,findings:[{...data.findings[0],trigger:'DIVIDE_BY_ZERO'}],evidence_refs:['nonce-test'],payload:{verdict:'incomplete',detail:'STATIC_ONLY'}}};
  assert.throws(()=>verifySmoke(smoke,{evidenceFile:path.join(dir,'evidence.md'),nonce:'nonce-test',model:'configured'}),{code:'evidence_not_read'});
  smoke.reads=[path.join(dir,'evidence.md')];assert.equal(verifySmoke(smoke,{evidenceFile:smoke.reads[0],nonce:'nonce-test',model:'configured'}),true);
  fs.writeFileSync(file,JSON.stringify({...event,permission_denials:[{tool_name:'Read'}]})+'\n');
  await assert.rejects(parseTranscript(file),{code:'permission_blocked'});
  fs.writeFileSync(file,JSON.stringify({...event,is_error:true,result:'usage quota reached'})+'\n');
  await assert.rejects(parseTranscript(file),{code:'quota_exhausted'});
  fs.writeFileSync(file,'{"type":"assistant"}\n');
  await assert.rejects(parseTranscript(file),{code:'invalid_result'});
});

test('executor configuration: explicit permission changes and atomic model allowlist extension',async t=>{
  const dir=temporary(t),file=path.join(dir,'host.json'),raw=readJson(path.join(TOOL_ROOT,'config/home.example.json'));
  raw.catalog=path.join(TOOL_ROOT,'config/roles.json');raw.providers['codex-local'].models={'gpt-6-astra':['low','medium','high','xhigh']};atomicJson(file,raw);
  const patch={enabled:true,provider:'codex-local',model:'gpt-5.6-luna',effort:'low',execution:'worker',access:'workspace-write',permissions:'full-access'};
  const original=fs.readFileSync(file,'utf8');
  await assert.rejects(editBindings(file,{changes:[{role:'executor',patch}],write:true}),{code:'unsupported_model'});
  assert.equal(fs.readFileSync(file,'utf8'),original);
  const change={role:'executor',patch,allow_model:true},preview=await editBindings(file,{changes:[change]});
  assert.ok(preview.changes.some(c=>c.field==='models'));assert.equal(fs.readFileSync(file,'utf8'),original);
  await editBindings(file,{revision:preview.revision,changes:[change],write:true});
  const selected=resolveRole(loadHost(file),'executor',dir);
  assert.equal(selected.model,'gpt-5.6-luna');assert.equal(selected.effort,'low');assert.equal(selected.role.permissions,'full-access');
  assert.deepEqual(readJson(file).providers['codex-local'].models['gpt-6-astra'],raw.providers['codex-local'].models['gpt-6-astra']);
  await editBindings(file,{changes:[{role:'executor',patch:{effort:'max'},allow_model:true}],write:true});
  assert.deepEqual(readJson(file).providers['codex-local'].models['gpt-5.6-luna'],['low','max']);
  await editBindings(file,{changes:[{role:'executor',patch:{effort:null}}],write:true});
  assert.equal(resolveRole(loadHost(file),'executor',dir).effort,null);
  await assert.rejects(editBindings(file,{changes:[{role:'reviewer',patch:{permissions:'full-access'}}],write:true}),{code:'permission_escalation'});
  await editBindings(file,{changes:[{role:'developer-basic',patch:{execution:'worker',access:'workspace-write',permissions:'full-access',provider:'claude-local',model:'claude-sonnet-5'}}],write:true});
  assert.equal(resolveRole(loadHost(file),'developer-basic',dir).role.can_delegate,false);
});
